### ISSUE TITLE
Make all login/create account layouts consistent throughout

### ISSUE THREAD

**Issue by nogainbar** [karmaradio/karma#150] opened 2017-05-26 16:50 UTC
Center the login boxes vertically 
and make sure the width is consistent for login page throughout the app

**Comment by nogainbar** [comment] 2017-05-30 15:59
hey @jonscottfilm,

Check out the login page, it is now consistent and I added a little more styling to it :)

<img width="1440" alt="screen shot 2017-05-30 at 16 56 46" src="https://cloud.githubusercontent.com/assets/12494147/26592649/449fd1ae-4559-11e7-8ce5-21029013d755.png">
<img width="1440" alt="screen shot 2017-05-30 at 16 56 54" src="https://cloud.githubusercontent.com/assets/12494147/26592650/469549a8-4559-11e7-8dda-606dfd01a4f6.png">
<img width="1440" alt="screen shot 2017-05-30 at 16 56 59" src="https://cloud.githubusercontent.com/assets/12494147/26592652/475e8c1e-4559-11e7-974b-f25664761dd2.png">

**Comment by nogainbar** [comment] 2017-05-30 16:09
@jonscottfilm also are you happy with how it look in terms of spaces between input fields? that relates also to issue #149

**Comment by jonscottfilm** [comment] 2017-05-30 16:11
Loving it! Spacing is better. In light of one thing per page, I wonder if First name & Last Name, could be separated a little more from Email & Password, albeit on the same page...? 

Comments: 
when are you thinking of implementing floating labels?
is it difficult to put a checkbox on the same line as text?
how are you feeling about the logo..?

**Comment by nogainbar** [comment] 2017-05-30 16:33
@jonscottfilm 
yup, agreed, added space between First name & Last Name from Email & Password :)

<img width="1440" alt="screen shot 2017-05-30 at 17 26 50" src="https://cloud.githubusercontent.com/assets/12494147/26593780/4401e01c-455d-11e7-8a1f-34e15e8b534c.png">

- Still need to go through priority1's, namely #156 and #163 and then Floating labels is currently priority2 but it can be the first priority two I tackle after those!
- It is not difficult but will make a separate issue for that :) we have quite a few of those and will want to style them together perhaps! (also mentioned in #151)
- The logo is great but I was thinking that we should probably say the name of the app somewhere on the login page? do you have a logotype and well as a symbol?

**Comment by jonscottfilm** [comment] 2017-05-30 17:14
Testing now.

Good point re app &/or company name. 
I was just planning to use Lato. 
Wanting to keep a low profile on Github until we absolutely _have_ to switch all mentions of Karma to engine.

**Comment by jonscottfilm** [comment] 2017-05-30 17:20
Log-in screen resizing does _vaguely_ funky thing at certain size, perhaps linked to the white area in the footer/background?

![image](https://cloud.githubusercontent.com/assets/28431542/26595816/8da7deb8-4564-11e7-968a-288a3a5e1741.png)


And on mobile, am unable to zoom to _not_ have it split by bottom of white container:

![image](https://cloud.githubusercontent.com/assets/28431542/26595771/71013df4-4564-11e7-8c57-3c9717060964.png)

**Comment by jonscottfilm** [comment] 2017-05-30 18:59
This works. 
Just not the re-sizing issues https://github.com/karmaradio/karma/issues/150#issuecomment-304948120, and possibly relocating 'Already have an account? - Login' to beneath the Create Account setup, (then consistent with login).

**Comment by nogainbar** [comment] 2017-05-30 21:07
good point! will look at it tomorrow, I think I know whats causing this :)

**Comment by jonscottfilm** [comment] 2017-05-31 13:16
@nogainbar - not sure what has been implemented yet... should I be seeing any changes/fixes. White card background doesn't resize well (bottom edge doesn't expand to stay behind text)

Bottom edge expanding, works here:
![image](https://cloud.githubusercontent.com/assets/28431542/26633511/9166e75e-460b-11e7-922f-ae6b29a12e0d.png)

But not here:
![image](https://cloud.githubusercontent.com/assets/28431542/26633535/a3c090c6-460b-11e7-99df-79a8146f5d2c.png)

or:
![image](https://cloud.githubusercontent.com/assets/28431542/26633550/b20daefc-460b-11e7-8558-7c95fea4589b.png)


**Widths of login screens are consistent, so can otherwise close issue.**

**Comment by nogainbar** [comment] 2017-05-31 14:13
@jonscottfilm fixed that issue and it should be ok now :) also moved 'Already have an account? - Login' to beneath the Create Account button

**Comment by jonscottfilm** [comment] 2017-05-31 14:31
Ok. 
That's not merged yet though, right?

**Comment by nogainbar** [comment] 2017-05-31 14:33
no, not yet but soon! the boys are on it ;)

**Comment by jonscottfilm** [comment] 2017-05-31 16:36
height issue still occurring, I'm afraid. I think it's _better_ than it was. It's not unusable, so not a priority - as much as it seems it might be for me! 

![image](https://cloud.githubusercontent.com/assets/28431542/26642781/f579d808-4626-11e7-99f4-b81852bae05f.png)

And I think we should look login screen appears on an actual mobile phone, now that it's centred vertically, you get the grey background at the top, at least when the address bar is still visible, scroll down it's fine, likely as intended:

![image](https://cloud.githubusercontent.com/assets/28431542/26642914/71fda74c-4627-11e7-9fb6-5c365ea90b14.png)

**Comment by JMurphyWeb** [comment] 2017-06-01 11:35
password reset need attention

**Comment by nogainbar** [comment] 2017-06-01 13:25
When zooming in still content overflow from card.

**Closed** 2017-06-01 15:51 UTC
Labels: awaiting-review, bug, priority-2, T4h, UX/UI
