### ISSUE TITLE
Create Document Merge Script

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#290] opened 2017-06-05 16:28 UTC
We need to create the script for merging the `pdf` with all of the `project`, `offer`, `startpack` and `user` data that will be run once it gets uploaded and the contractor is happy with the contract as it stands.

- [ ] create merging script

**Comment by JMurphyWeb** [comment] 2017-06-07 11:26
closing as duplicate of #309

**Closed by JMurphyWeb** 2017-06-07 11:26 UTC
Labels: duplicate, enhancement, T1d, technical
