### ISSUE TITLE
Accept/Reject Email Flow

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#23] opened 2017-05-08 16:43 UTC
When a contractor either accepts or rejects an offer, the project manager should be notified through email. This will allow the PM to act promptly and effectively.

**Comment by jonscottfilm** [comment] 2017-05-31 09:00
can now test, now I know there is a way....!

**Comment by jonscottfilm** [comment] 2017-05-31 12:25
Accept offer works.

Reject offer, I get an internal server error.

![image](https://cloud.githubusercontent.com/assets/28431542/26631752/76c79238-4604-11e7-9ce8-10cc4d89ed22.png)

**Comment by jackcarlisle** [comment] 2017-05-31 12:56
@jonscottfilm will look into this!

**Comment by jonscottfilm** [comment] 2017-05-31 16:37
will test

**Comment by jonscottfilm** [comment] 2017-06-02 17:43
Jono still testing, but not sure _any_ 'This contractor has accepted or rejected this offer' emails have been received by PM...

**Comment by jonscottfilm** [comment] 2017-06-04 17:34
Sure this is duplicate of #11 .

**Comment by JMurphyWeb** [comment] 2017-06-05 10:06
@jonscottfilm this should be fine.

If 1 specific bug is the only one preventing several issues being closed, it is fine to highlight that in the issue most related and close the rest. We will pick up on that bug as long as it is in our Milestone and it has a  'Bug' label 🐛

**Comment by jonscottfilm** [comment] 2017-06-06 21:27
Working!

**Closed by jonscottfilm** 2017-06-06 21:27 UTC
Labels: please-test, T4h, user-story
