### ISSUE TITLE
Derived Offer Fields

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#100] opened 2017-05-22 15:02 UTC
As a project manager,
I want to be able to check the calculated values from my inputs,
So that I can confirm they are what I want them to be

**Comment by JMurphyWeb** [comment] 2017-05-24 09:29
@jonscottfilm by clicking on an offer, you should be able to see (and verify!!!) the calculated fields

**Comment by jonscottfilm** [comment] 2017-05-24 14:26
Checking calculated fields now. 

In the meantime, it needs Project Name in this view, either as a heading, or within the offer, to identify from other projects.

https://karmaradio.herokuapp.com/projects/10/offers/9
![image](https://cloud.githubusercontent.com/assets/28431542/26408290/46920e96-4095-11e7-98b8-4fef82ca16fc.png)

**Comment by jonscottfilm** [comment] 2017-05-24 15:06
Calculations are correct for 10.77% project holiday rate.

Also correct for 12.77%. Note that 7th day rate shows as 1.0e3 instead of 1000!
![image](https://cloud.githubusercontent.com/assets/28431542/26410324/d0cf529e-409a-11e7-8e43-b9f0b03b462d.png)

**Comment by jonscottfilm** [comment] 2017-05-24 15:13
Also, 'Holiday pay per week' field is repeated twice. Appears for 2nd time at end of Fees section. 
Rather than remove, let's show 'Project holiday rate' instead. Then the user is aware, and can check if they like!?

In 'Edit offer', this field _label_ is incorrect: Fee per day including holiday (per diem). Not seen it elsewhere.
Delete (per diem) - that is the 'per day' out-of-pocket expenses paid when staying away from home.

Also, maybe since changing this label, the Recipient field formatting has gone awry:
![image](https://cloud.githubusercontent.com/assets/28431542/26410718/f8a3ea36-409b-11e7-9d88-bc73312d9c48.png)

**Comment by jonscottfilm** [comment] 2017-05-24 15:47
@beccacca  spotted: 

If 6-day Working Week is selected, the 6th day multiplier fields are no longer applicable, because it has become part of the deal. Doesn't _hurt_ to still show them (ideally not show in offer), so long as PM doesn't change 6th day multiplier field to anything other than 1.

_However_, 6th day rate _does_ still apply for 5.5 day deal (i.e. the 11th day within a fortnight)

New issue (?) for the backlog:
Can't hide 6th day fields based on selection, as it differs in each scenario.
Instead, can we make the 6th day multiplier uneditable in the create/edit offer views, when a 5.5. or 6 day deal is selected in 'Working Week' field?

**Comment by jonscottfilm** [comment] 2017-05-24 16:52
Issue brief:

_As a project manager,
I want to be able to check the calculated values from my inputs,
So that I can confirm they are what I want them to be_

We know the calculations work (Becca just double-checking), but the PM doesn't _see_ the calculated values, until the offer has gone off to the recipient. Yes, he can then check in the offers dash, but it's too late then. 
Although, I suppose he can always edit it, and resend. Just would be good to have a fool-proof - 'this is the deal you've created - one last check?! Good to send...'

**Comment by jonscottfilm** [comment] 2017-05-25 13:53
Create new issues for these (https://github.com/karmaradio/karma/issues/100#issuecomment-303766027 & https://github.com/karmaradio/karma/issues/100#issuecomment-303784938), 
and then close this one?

**Comment by JMurphyWeb** [comment] 2017-05-26 09:55
@jonscottfilm I think so..

They are both good points, definitely worth issuing and working out how important they are.  As a user story issue for the second, something like:

> As a PM, I want to be able to view the offer details before sending to the contractor, so i can review my inputed data and verify the calculated values.

**Comment by jackcarlisle** [comment] 2017-05-30 15:33
@jonscottfilm did new issues get created for https://github.com/karmaradio/karma/issues/100#issuecomment-303766027 and https://github.com/karmaradio/karma/issues/100#issuecomment-303784938?

**Comment by jonscottfilm** [comment] 2017-05-30 15:48
Started, but got swept away! Will create.

**Comment by jackcarlisle** [comment] 2017-05-30 15:55
@jonscottfilm great stuff! Please close this once you have

**Closed** 2017-05-31 13:00 UTC
Labels: T1h, user-story
